# Generated by Django 4.2.5 on 2023-10-06 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='mobilenumber',
        ),
        migrations.AddField(
            model_name='artist',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('Others', 'OTHERS')], default='Unknown', max_length=20),
        ),
        migrations.AddField(
            model_name='artist',
            name='phonenumber',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='phonenumber',
            field=models.CharField(default='Unknown', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('Others', 'OTHERS')], default='Unknown', max_length=20),
        ),
    ]
