# Generated by Django 4.2.5 on 2023-10-06 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_remove_customer_mobilenumber_artist_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
    ]
