# Generated by Django 4.2.5 on 2023-10-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_rename_name_customer_username_artist_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
