# Generated by Django 4.2.5 on 2023-11-04 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0014_alter_products_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image',
        ),
    ]
