# Generated by Django 4.2.5 on 2023-11-04 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0021_customerprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='bio',
            new_name='artistbio',
        ),
        migrations.RenameField(
            model_name='artistprofile',
            old_name='name',
            new_name='artistname',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='bio',
            new_name='customerbio',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='name',
            new_name='customername',
        ),
    ]
