# Generated by Django 4.2.5 on 2023-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_rename_bio_artistprofile_artistbio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='artistimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
