# Generated by Django 4.2.5 on 2023-12-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0023_artistprofile_artistimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='artistimage',
        ),
        migrations.AddField(
            model_name='artist',
            name='artistimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
