# Generated by Django 4.2.5 on 2023-12-07 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_remove_artistprofile_artistimage_artist_artistimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='artistbio',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='customerbio',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artistimage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='category',
            field=models.CharField(choices=[('Painter', 'Painter'), ('Sculptur', 'Sculpture')], default='', max_length=25),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('Others', 'OTHERS')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='phonenumber',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(default='customer123', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('Others', 'OTHERS')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='phonenumber',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='artistname',
            field=models.OneToOneField(default='artist', on_delete=django.db.models.deletion.CASCADE, to='adminapp.artist'),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='customername',
            field=models.OneToOneField(default='customer', on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer'),
        ),
    ]
