# Generated by Django 4.2.5 on 2023-12-07 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0025_remove_artistprofile_artistbio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artistprofile',
            old_name='phonenumber',
            new_name='phonenumber1',
        ),
        migrations.RenameField(
            model_name='customerprofile',
            old_name='phonenumber',
            new_name='phonenumber2',
        ),
    ]
