# Generated by Django 4.2.5 on 2023-12-07 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0027_alter_artistprofile_phonenumber1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='artistimage',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='artistname',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='category',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='phonenumber1',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='verified',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='customername',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='phonenumber2',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='verified',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artist',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminapp.artist'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='social_media_links',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customer',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='adminapp.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='favorite_artists',
            field=models.ManyToManyField(blank=True, to='adminapp.artist'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='interests',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
