# Generated by Django 4.2.5 on 2023-12-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0028_remove_artistprofile_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='artist',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='portfolio_url',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='social_media_links',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='favorite_artists',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='interests',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artistbio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='artistname',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.artist'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customerbio',
            field=models.TextField(default=' '),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='customername',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.customer'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
