# Generated by Django 4.2.5 on 2023-12-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0029_remove_artistprofile_artist_remove_artistprofile_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerprofile',
            name='customername',
        ),
        migrations.DeleteModel(
            name='ArtistProfile',
        ),
        migrations.DeleteModel(
            name='CustomerProfile',
        ),
    ]
