# Generated by Django 4.2.5 on 2023-12-09 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0030_remove_customerprofile_customername_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='phonenumber',
            new_name='phonenumber1',
        ),
    ]
